# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: adrenth.redirect::lang.redirect.reorder_redirects

# Attribute name
nameFrom: from_url

# Model Class name
modelClass: Adrenth\Redirect\Models\Redirect

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
